spring:
  kafka:
    streams:
      bootstrap-servers: "localhost:9092"
      application-id: "spring-kafka-streams-fiveminwindow-id"
      properties:
        num:
          stream:
            threads: "1"
        default:
          deserialization:
            exception:
              handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
          production:
            exception:
              #handler: org.apache.kafka.streams.errors.DefaultProductionExceptionHandler
              handler: com.harvicom.kafkastreams.fiveminwindow.processor.LogAndContinueProductionExceptionHandler
  