spring:
  kafka:
    streams:
      bootstrap-servers: "localhost:9092"
      application-id: "spring-kafka-streams-datetime-fix-id"
      client-id: "spring-kafka-streams-datetime-fix"
      properties:
        num:
          stream:
            threads: "10"
        default:
          deserialization:
            exception:
              handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
          production:
            exception:
              handler: org.apache.kafka.streams.errors.DefaultProductionExceptionHandler